### ISSUE TITLE
Issue with BIOS update Reboot

### ISSUE THREAD

**Issue by ehousse** [philjorgensen/Intune#3]
Seems like the system isn't triggering the reboot properly in the event a BIOS update, since ESP has it set to block, the autopilot process errors out.  The app per your original guide is configured with the same settings, its W11.   When the device is rebooted after failing the "Device Config Apps" step, the BIOS update proceeds as normal, after retrying the app doesn't trigger an error now that the BIOS is the latest version.

I use the registry rule for self-deployment, for the most part has worked fine until recently.  The version of Lenovo Thin Installer is the same, unless Microsoft changed something in the autopilot process or Lenovo changed something in the BIOS update application process, we haven't changed anything since early 2024.

**Comment by philjorgensen** [comment]
@ehousse 
Are you referring to the Get-LnvUpdates solution? What's the MTM of the system you're testing this on?

**Comment by ehousse** [comment]
Yes Get-LnvUpdates prior to your change 2 months ago, seems like the logs claim that there was a failure in detection, but only if it applied BIOS.  What do you mean by MTM?

**Comment by philjorgensen** [comment]
Machine Type Model (first 4 characters).

**Comment by ehousse** [comment]
21HM/20UB/20TA same issue across each model, failure after the app runs, manual reboot BIOS applies, next autopilot attempt no issues.

**Comment by philjorgensen** [comment]
I don't have these models on-hand at the moment, but I tested on another model that needed a BIOS update and my AP deployment went through successfully. This was a pre-provisioned deployment, which is noted as recommended in the article. Did you do a pre-provisioned or user-driven deployment?

**Comment by ehousse** [comment]
Pre-Provisioned (Self-Deploy) it is odd, it failed twice previously yesterday and a couple of weeks ago, seems to be working fine on the same model, it failed on twice.
